name: GitHub Action for building DolphinOS ISO

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build_iso:
    name: Create and build DolphinOS ISO
    runs-on: self-hosted

    container:
      image: ghcr.io/dolphinos-development/dolphinos-buildsystem-images/arch_iso_builder_image:latest
      options: --privileged
      env:
        TZ: Europe/Madrid

    steps:
      - name: Set current date and hour as environment variable
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

      - name: Checkout main branch 
        uses: actions/checkout@v5
        with:
          ref: main
          path: repo
      - name: Fix workspace permissions
        working-directory: repo
        run: sudo chown -R builduser:builduser .
      - name: Download and copy system packages to archiso
        working-directory: repo
        run: |
          mkdir -p archiso/airootfs/var/dolphinos-packages
          mkdir pkgs
          sudo pacman -Syw --noconfirm --cachedir pkgs dolphinos-configs dolphinos-dolphin-data
          cp pkgs/dolphinos-configs*.pkg.tar.zst archiso/airootfs/var/dolphinos-packages/dolphinos-configs.pkg.tar.zst
          cp pkgs/dolphinos-dolphin-data*.pkg.tar.zst archiso/airootfs/var/dolphinos-packages/dolphinos-dolphin-data.pkg.tar.zst
      - name: Build ISO
        working-directory: repo
        run: |
          rm -rf work
          rm -rf build
          mkdir work
          mkdir build
          sudo mkarchiso -v -w work -o build archiso
          sudo rm -rf work
      - name: Upload ISO to Sourceforge Releases
        working-directory: repo
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t ssh-ed25519 frs.sourceforge.net > ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/dolphinos*.iso dolphinos@frs.sourceforge.net:/home/frs/project/dolphinos/DolphinOS
        env:
          SSH_KEY: ${{ secrets.SOURCEFORGE_PRIVATE_KEY }}

      - name: Checkout NVIDIA branch
        uses: actions/checkout@v5
        with:
          ref: nvidia
          path: repo-nvidia
      - name: Fix workspace permissions (NVIDIA)
        working-directory: repo-nvidia
        run: sudo chown -R builduser:builduser .
      - name: Download and copy system packages to archiso
        working-directory: repo-nvidia
        run: |
          mkdir -p archiso/airootfs/var/dolphinos-packages
          mkdir pkgs
          sudo pacman -Syw --noconfirm --cachedir pkgs dolphinos-configs-nvidia dolphinos-dolphin-data
          cp pkgs/dolphinos-configs-nvidia*.pkg.tar.zst archiso/airootfs/var/dolphinos-packages/dolphinos-configs-nvidia.pkg.tar.zst
          cp pkgs/dolphinos-dolphin-data*.pkg.tar.zst archiso/airootfs/var/dolphinos-packages/dolphinos-dolphin-data.pkg.tar.zst
      - name: Build NVIDIA ISO
        working-directory: repo-nvidia
        run: |
          mkdir work
          mkdir build
          sudo mkarchiso -v -w work -o build archiso
          sudo rm -rf work
      - name: Upload NVIDIA ISO to Sourceforge releases
        working-directory: repo-nvidia
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t ssh-ed25519 frs.sourceforge.net > ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/dolphinos*.iso dolphinos@frs.sourceforge.net:/home/frs/project/dolphinos/DolphinOS-NVIDIA
        env:
          SSH_KEY: ${{ secrets.SOURCEFORGE_PRIVATE_KEY }}
      
      - name: Publish Sourceforge link to releases
        uses: ncipollo/release-action@v1
        with:
          body: "Automatically built latest ISO\nLink: https://sourceforge.net/projects/dolphinos"
          tag: "DolphinOS-ISO-${{ env.NOW }}"
          allowUpdates: true
          makeLatest: true
